M48
; DRILL file {KiCad 9.0.5} date 2025-12-09T21:28:29-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-09T21:28:29-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X142.9Y-48.61
X142.9Y-54.39
T2
X72.5Y-100.5
X153.0Y-49.0
M30
